export const TAX_RATES = {
    Canada: {
        Alberta: { rate: 0.05, name: "GST 5%" },
        "British Columbia": { rate: 0.12, name: "GST+PST 12%" },
        Manitoba: { rate: 0.12, name: "GST+RST 12%" },
        "New Brunswick": { rate: 0.15, name: "HST 15%" },
        "Newfoundland and Labrador": { rate: 0.15, name: "HST 15%" },
        "Northwest Territories": { rate: 0.05, name: "GST 5%" },
        "Nova Scotia": { rate: 0.15, name: "HST 15%" },
        Nunavut: { rate: 0.05, name: "GST 5%" },
        Ontario: { rate: 0.13, name: "HST 13%" },
        "Prince Edward Island": { rate: 0.15, name: "HST 15%" },
        Quebec: { rate: 0.14975, name: "GST+QST 14.975%" },
        Saskatchewan: { rate: 0.11, name: "GST+PST 11%" },
        Yukon: { rate: 0.05, name: "GST 5%" },
    },
    "United States": {
        Alabama: { rate: 0.04, name: "Sales Tax 4%" },
        Alaska: { rate: 0, name: "Sales Tax 0%" },
        Arizona: { rate: 0.056, name: "Sales Tax 5.6%" },
        Arkansas: { rate: 0.065, name: "Sales Tax 6.5%" },
        California: { rate: 0.0725, name: "Sales Tax 7.25%" },
        Colorado: { rate: 0.029, name: "Sales Tax 2.9%" },
        Connecticut: { rate: 0.0635, name: "Sales Tax 6.35%" },
        Delaware: { rate: 0, name: "Sales Tax 0%" },
        Florida: { rate: 0.06, name: "Sales Tax 6%" },
        Georgia: { rate: 0.04, name: "Sales Tax 4%" },
        Hawaii: { rate: 0.04, name: "Sales Tax 4%" },
        Idaho: { rate: 0.06, name: "Sales Tax 6%" },
        Illinois: { rate: 0.0625, name: "Sales Tax 6.25%" },
        Indiana: { rate: 0.07, name: "Sales Tax 7%" },
        Iowa: { rate: 0.06, name: "Sales Tax 6%" },
        Kansas: { rate: 0.065, name: "Sales Tax 6.5%" },
        Kentucky: { rate: 0.06, name: "Sales Tax 6%" },
        Louisiana: { rate: 0.0445, name: "Sales Tax 4.45%" },
        Maine: { rate: 0.055, name: "Sales Tax 5.5%" },
        Maryland: { rate: 0.06, name: "Sales Tax 6%" },
        Massachusetts: { rate: 0.0625, name: "Sales Tax 6.25%" },
        Michigan: { rate: 0.06, name: "Sales Tax 6%" },
        Minnesota: { rate: 0.06875, name: "Sales Tax 6.875%" },
        Mississippi: { rate: 0.07, name: "Sales Tax 7%" },
        Missouri: { rate: 0.04225, name: "Sales Tax 4.225%" },
        Montana: { rate: 0, name: "Sales Tax 0%" },
        Nebraska: { rate: 0.055, name: "Sales Tax 5.5%" },
        Nevada: { rate: 0.0685, name: "Sales Tax 6.85%" },
        "New Hampshire": { rate: 0, name: "Sales Tax 0%" },
        "New Jersey": { rate: 0.06625, name: "Sales Tax 6.625%" },
        "New Mexico": { rate: 0.05125, name: "Sales Tax 5.125%" },
        "New York": { rate: 0.04, name: "Sales Tax 4%" },
        "North Carolina": { rate: 0.0475, name: "Sales Tax 4.75%" },
        "North Dakota": { rate: 0.05, name: "Sales Tax 5%" },
        Ohio: { rate: 0.0575, name: "Sales Tax 5.75%" },
        Oklahoma: { rate: 0.045, name: "Sales Tax 4.5%" },
        Oregon: { rate: 0, name: "Sales Tax 0%" },
        Pennsylvania: { rate: 0.06, name: "Sales Tax 6%" },
        "Rhode Island": { rate: 0.07, name: "Sales Tax 7%" },
        "South Carolina": { rate: 0.06, name: "Sales Tax 6%" },
        "South Dakota": { rate: 0.045, name: "Sales Tax 4.5%" },
        Tennessee: { rate: 0.07, name: "Sales Tax 7%" },
        Texas: { rate: 0.0625, name: "Sales Tax 6.25%" },
        Utah: { rate: 0.0485, name: "Sales Tax 4.85%" },
        Vermont: { rate: 0.06, name: "Sales Tax 6%" },
        Virginia: { rate: 0.053, name: "Sales Tax 5.3%" },
        Washington: { rate: 0.065, name: "Sales Tax 6.5%" },
        "West Virginia": { rate: 0.06, name: "Sales Tax 6%" },
        Wisconsin: { rate: 0.05, name: "Sales Tax 5%" },
        Wyoming: { rate: 0.04, name: "Sales Tax 4%" },
    },
};

export const COUNTRIES = [
    { value: "Canada", label: "Canada" },
    { value: "United States", label: "United States" },
    { value: "Other", label: "Other" },
];

export const PROVINCES = {
    Canada: Object.keys(TAX_RATES["Canada"]).map((p) => ({
        value: p,
        label: p,
    })),
    "United States": Object.keys(TAX_RATES["United States"]).map((p) => ({
        value: p,
        label: p,
    })),
    Other: [],
};
