export const MODELS = {
    ACURA: [
        "CL",
        "CSX",
        "EL",
        "ILX",
        "ILX DYNAMIC",
        "ILX HYBRID",
        "INTEGRA",
        "LEGEND",
        "MDX",
        "RDX",
        "RL",
        "RLX",
        "RSX",
        "SLX",
        "TL",
        "TLX",
        "TSX",
        "VIGOR",
    ],
    AUDI: [
        "A3",
        "A4",
        "A5",
        "A6",
        "A7",
        "A8",
        "ALLROAD",
        "Q5",
        "Q7",
        "RS4",
        "RS5",
        "S3",
        "S4",
        "S5",
        "S6",
        "S7",
        "SQ5",
        "TT",
    ],
    BMW: [
        "1 SERIES",
        "2 SERIES",
        "3 SERIES",
        "4 SERIES",
        "5 SERIES",
        "6 SERIES",
        "7 SERIES",
        "I3",
        "M1",
        "M2",
        "M3",
        "M4",
        "M5",
        "M6",
        "M7",
        "M8",
        "X1",
        "X2",
        "X3",
        "X4",
        "X5",
        "X6",
        "X7",
        "Z3",
        "Z4",
    ],
    BUICK: [
        "ALLURE",
        "CASCADA",
        "CENTURY",
        "ENCLAVE",
        "ENCORE (BUICK)",
        "ENVISION",
        "LACROSSE",
        "LESABRE",
        "LUCERNE",
        "PARK AVENUE",
        "RAINIER",
        "REGAL",
        "RENDEZVOUS",
        "RIVIERA",
        "TERRAZA",
        "VERANO",
    ],
    CADILLAC: [
        "ATS",
        "CTS",
        "DEVILLE",
        "DTS",
        "ELDORADO",
        "ESCALADE",
        "ESCALADE ESV",
        "ESCALADE EXT",
        "ESCALADE HYBRID",
        "SEVILLE",
        "SRX",
        "STS",
        "XLR",
        "XT4",
        "XT5",
        "XT6",
        "XTS",
    ],
    CHEVROLET: [
        "ASTRO VAN",
        "AVALANCHE",
        "AVEO",
        "BLAZER",
        "CAMARO",
        "CAPTIVA",
        "CAVALIER",
        "CITY EXPRESS",
        "COBALT",
        "COLORADO",
        "CORVETTE",
        "CRUZE",
        "EQUINOX",
        "IMPALA",
        "LUMINA",
        "MALIBU",
        "METRO",
        "MONTE CARLO",
        "NOVA",
        "PRIZM",
        "S10",
        "SILVERADO 1500",
        "SILVERADO 2500",
        "SILVERADO 3500",
        "SILVERADO EV",
        "SONIC",
        "SPARK",
        "SPRINT",
        "SUBURBAN",
        "TAHOE",
        "TRACKER",
        "TRAILBLAZER",
        "TRAX",
        "UPLANDER",
        "VAN EXPRESS",
        "VENTURE",
        "VOLT",
    ],
    CHRYSLER: [
        "200",
        "300",
        "ASPEN",
        "CIRRUS",
        "CONCORDE",
        "INTREPID",
        "NEON",
        "PACIFICA",
        "PT CRUISER",
        "SEBRING",
        "TOWN AND COUNTRY",
        "VOYAGER",
    ],
    DODGE: [
        "AVENGER",
        "CALIBER",
        "CARAVAN",
        "CHALLENGER",
        "CHARGER",
        "DAKOTA PICKUP",
        "DART",
        "DURANGO",
        "INTREPID",
        "JOURNEY",
        "MAGNUM",
        "NEON",
        "NITRO",
        "SPIRIT",
        "STEALTH",
        "STRATUS",
        "VAN DODGE SPRINTER",
    ],
    FORD: [
        "500",
        "C MAX",
        "CONTOUR",
        "ECOSPORT",
        "EDGE",
        "ESCAPE",
        "ESCORT",
        "EXCURSION",
        "EXPEDITION",
        "EXPLORER",
        "FESTIVA",
        "FIESTA",
        "FLEX",
        "FOCUS",
        "FREESTAR",
        "FREESTYLE",
        "FUSION",
        "MUSTANG",
        "PICKUP F150",
        "PICKUP F250",
        "PICKUP F350",
        "PICKUP F450",
        "PICKUP F550",
        "PICKUP RANGER",
        "TAURUS",
        "THUNDERBIRD",
        "TRANSIT CONNECT",
        "TRANSIT 150 CARGO VAN",
        "TRANSIT 250 CARGO VAN",
        "TRANSIT 350 CARGO VAN",
        "VAN E350",
        "VAN E450",
        "VAN ECONOLINE",
        "WINDSTAR",
        "ZX2",
    ],
    GMC: [
        "ACADIA",
        "CANYON",
        "ENVOY",
        "PICKUP DENALI 1500",
        "PICKUP DENALI 2500",
        "PICKUP DENALI 3500",
        "PICKUP SIERRA 1500",
        "PICKUP SIERRA 2500",
        "PICKUP SIERRA 3500",
        "PICKUP SIERRA 4500",
        "PICKUP SIERRA 5500",
        "PICKUP SIERRA 6500",
        "PICKUP SIERRA EV",
        "SAFARI VAN",
        "SAVANA VAN",
        "YUKON",
    ],
    HONDA: [
        "ACCORD",
        "CIVIC",
        "CLARITY",
        "CRV",
        "CRX",
        "CRZ",
        "DEL SOL",
        "ELEMENT",
        "FIT",
        "HRV",
        "INSIGHT",
        "ODYSSEY",
        "PASSPORT",
        "PILOT",
        "PRELUDE",
        "RIDGELINE",
        "S2000",
    ],
    HUMMER: ["H2", "H3", "H3T"],
    HYUNDAI: [
        "ACCENT",
        "AZERA",
        "ELANTRA",
        "ENTOURAGE",
        "EXCEL",
        "G80",
        "GENESIS",
        "IONIQ",
        "KONA",
        "PALISADE",
        "SANTA CRUZ",
        "SANTA FE",
        "SCOUPE",
        "SONATA",
        "TIBURON",
        "TUCSON",
        "VELOSTER",
        "VENUE",
        "VERACRUZ",
        "XG300",
        "XG350",
    ],
    INFINITI: [
        "EX35",
        "EX37",
        "EX 45",
        "FX50",
        "G20",
        "G25",
        "G35",
        "G37",
        "I30",
        "I35",
        "J30",
        "JX35",
        "M35",
        "M35H",
        "M37",
        "M45",
        "Q40",
        "Q50",
        "Q60",
        "Q70",
        "QX30",
        "QX40",
        "QX50",
        "QX60",
        "QX70",
        "QX80",
    ],
    ISUZU: [
        "AMIGO",
        "ASCENDER",
        "IMPULSE",
        "ISUZU PICKUP",
        "OASIS",
        "RODEO",
        "RODEO SPORT",
        "STYLUS",
        "TROOPER",
        "VEHICROSS",
    ],
    JEEP: [
        "CHEROKEE",
        "COMMANDER",
        "COMPASS",
        "GLADIATOR",
        "GRAND CHEROKEE",
        "LIBERTY",
        "PATRIOT",
        "RENEGADE",
        "WRANGLER",
    ],
    KIA: [
        "AMANTI",
        "CADENZA",
        "CARNIVAL",
        "FORTE",
        "K5",
        "MAGENTIS",
        "NIRO",
        "OPTIMA",
        "RIO",
        "RONDO",
        "RX-V",
        "SEDONA",
        "SELTOS",
        "SEPHIA",
        "SORENTO",
        "SOUL",
        "SPECTRA",
        "SPORTAGE",
        "TELLURIDE",
    ],
    LEXUS: [
        "CT200H",
        "ES250",
        "ES300",
        "ES300H",
        "ES330",
        "ES350",
        "GS200T",
        "GS300",
        "GS350",
        "GS400",
        "GS430",
        "GS450H",
        "GS460",
        "GS F",
        "GS TURBO",
        "GX460",
        "GX470",
        "HS250H",
        "IS200T",
        "IS200T F SPORT",
        "IS250C CONVERTIBLE",
        "IS250 SEDAN",
        "IS300",
        "IS350C CONVERTIBLE",
        "IS350 SEDAN",
        "IS F",
        "LS400",
        "LS430",
        "LS460",
        "LS500",
        "LS500H",
        "LS600H",
        "LX470",
        "LX570",
        "NX200T",
        "NX300",
        "NX300H",
        "RC200T",
        "RC300",
        "RC300 TURBO",
        "RC350",
        "RC F",
        "RC TURBO",
        "RX300",
        "RX330",
        "RX350",
        "RX350L",
        "RX400H",
        "RX450H",
        "RX450HL",
        "UX200",
        "UX250H",
    ],
    LINCOLN: [
        "AVIATOR",
        "BLACKWOOD",
        "CONTINENTAL",
        "CORSAIR",
        "LS",
        "MARK LT",
        "MKC",
        "MKS",
        "MKT",
        "MKX",
        "MKZ",
        "NAUTILUS",
        "NAVIGATOR",
        "TOWN CAR",
        "ZEPHYR",
    ],
    MAZDA: [
        "626",
        "929",
        "CRONOS",
        "CX-3",
        "CX-30",
        "CX-5",
        "CX-50",
        "CX-7",
        "CX-9",
        "MAZDA 2",
        "MAZDA 3",
        "MAZDA 5",
        "MAZDA 6",
        "MAZDA PICKUP",
        "MIATA",
        "MILLENIA",
        "MPV",
        "MX-3",
        "MX-5 MIATA",
        "MX-6",
        "PROTEGE",
        "RX-7",
        "RX-8",
        "TRIBUTE",
    ],
    MERCEDES: [
        "300",
        "A CLASS",
        "B CLASS",
        "C CLASS",
        "CL",
        "CLA",
        "CLK",
        "CLS",
        "E CLASS",
        "G CLASS",
        "GL",
        "GLA",
        "GLB",
        "GLC",
        "GLE",
        "GLK",
        "GLS",
        "ML",
        "R CLASS",
        "S CLASS",
        "SL",
        "SLK",
        "SPRINTER 1500",
        "SPRINTER 2500",
        "SPRINTER 3500",
    ],
    MERCURY: [
        "COUGAR",
        "GRAND MARQUIS",
        "MARAUDER",
        "MARINER",
        "MILAN",
        "MONTEGO",
        "MONTEREY",
        "MOUNTAINEER",
        "MYSTIQUE",
        "SABLE",
        "TRACER",
        "VILLAGER",
    ],
    MITSUBISHI: [
        "3000GT",
        "DIAMANTE",
        "ECLIPSE",
        "ENDEAVOR",
        "EXPO",
        "GALANT",
        "LANCER",
        "MIRAGE",
        "MITSUBISHI",
        "MONTERO",
        "OUTLANDER",
        "RAIDER",
        "RVR",
        "SIGMA",
    ],
    NISSAN: [
        "200SX",
        "240SX",
        "350Z",
        "370Z",
        "ALTIMA",
        "ARMADA",
        "AXXESS",
        "CUBE",
        "FRONTIER PICKUP",
        "HARDBODY PICKUP",
        "JUKE",
        "KICKS",
        "LEAF",
        "MAXIMA",
        "MICRA (CANADA)",
        "MURANO",
        "NV1500",
        "NV200",
        "NV2500",
        "NV3500",
        "PATHFINDER",
        "QASHQAI",
        "QUEST",
        "ROGUE",
        "SENTRA",
        "STANZA",
        "TITAN PICKUP",
        "VERSA",
        "XTERRA",
        "XTRAIL",
    ],
    PONTIAC: [
        "AZTEK",
        "BONNEVILLE",
        "G3",
        "G5",
        "G6",
        "G8",
        "GRAND AM",
        "GRAND PRIX",
        "MONTANA",
        "PURSUIT",
        "SOLSTICE",
        "SUNBIRD",
        "SUNFIRE",
        "TORRENT",
        "TRANS SPORT",
        "VIBE",
        "WAVE",
    ],
    RAM: [
        "CARGO VAN",
        "DAKOTA",
        "PICKUP RAM 1500",
        "PICKUP RAM CLASSIC",
        "PICKUP RAM 2500",
        "PICKUP RAM 3500",
        "PICKUP RAM 4500",
        "PICKUP RAM 5500",
        "PROMASTER 1500",
        "PROMASTER 2500",
        "PROMASTER 3500",
        "PROMASTER CITY",
    ],
    SATURN: [
        "ASTRA",
        "AURA",
        "ION COUPE",
        "OUTLOOK",
        "RELAY",
        "SATURN",
        "SKY",
        "VUE",
    ],
    SUBARU: [
        "ASCENT",
        "BAJA",
        "BRZ",
        "CROSSTREK",
        "FORESTER",
        "IMPREZA",
        "JUSTY",
        "LEGACY",
        "OUTBACK",
        "SVX",
        "WRX",
        "XV",
    ],
    SUZUKI: [
        "AERIO",
        "EQUATOR",
        "ESTEEM",
        "GRAND VITARA",
        "SIDEKICK",
        "SWIFT",
        "SX4",
        "VITARA",
        "XL-7",
        "XL7",
    ],
    TESLA: ["MODEL 3", "MODEL S", "MODEL X", "MODEL Y", "CYBERTRUCK"],
    TOYOTA: [
        "4 RUNNER",
        "86 COUPE",
        "AVALON",
        "BZ4X",
        "CAMRY",
        "CELICA",
        "C-HR",
        "COROLLA",
        "CRESSIDA",
        "ECHO",
        "FJ CRUISER",
        "GR SUPRA",
        "HIGHLANDER",
        "LAND CRUISER",
        "MATRIX",
        "MR2",
        "PASEO",
        "PREVIA",
        "PRIUS",
        "RAV4",
        "SEQUOIA",
        "SIENNA",
        "SOLARA",
        "SUPRA",
        "T100 PICKUP",
        "TACOMA",
        "TERCEL",
        "TOYOTA VAN",
        "TUNDRA 4WD",
        "VENZA",
        "YARIS",
    ],
    VOLKSWAGEN: [
        "ATLAS",
        "BEETLE",
        "CABRIO",
        "CC",
        "EOS",
        "GOLF",
        "JETTA",
        "PASSAT",
        "RABBIT",
        "TAOS",
        "TIGUAN",
        "TOUAREG",
    ],
    VOLVO: [
        "850",
        "C30",
        "C70",
        "S40",
        "S60",
        "S70",
        "S80",
        "S90",
        "V40",
        "V50",
        "V60",
        "V70",
        "V90",
        "XC40",
        "XC60",
        "XC70",
        "XC90",
    ],
};
